// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ysJdpTVmacTyj9gGnz7bW7UB5fkZ1ow',
    appId: '1:288585933876:web:ca77c44894bf9873de5661',
    messagingSenderId: '288585933876',
    projectId: 'loginsignup1-1b048',
    authDomain: 'loginsignup1-1b048.firebaseapp.com',
    storageBucket: 'loginsignup1-1b048.appspot.com',
    measurementId: 'G-VTVWMMR8LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKsw_HIzU84eSprmIEhD6V_O0aIfY-_Tg',
    appId: '1:288585933876:android:453ea1f043833a86de5661',
    messagingSenderId: '288585933876',
    projectId: 'loginsignup1-1b048',
    storageBucket: 'loginsignup1-1b048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuOdq_Au6ks-ssS2UglFT4GFxVCfWzr3E',
    appId: '1:288585933876:ios:199d7c7f54d75de9de5661',
    messagingSenderId: '288585933876',
    projectId: 'loginsignup1-1b048',
    storageBucket: 'loginsignup1-1b048.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuOdq_Au6ks-ssS2UglFT4GFxVCfWzr3E',
    appId: '1:288585933876:ios:b8c27a7625fdd084de5661',
    messagingSenderId: '288585933876',
    projectId: 'loginsignup1-1b048',
    storageBucket: 'loginsignup1-1b048.appspot.com',
    iosBundleId: 'com.example.firestore.RunnerTests',
  );
}
